"""
Tripo Convert - Convert and optimize 3D models generated by Tripo API

Supports: format conversion, face reduction, quad mesh, UV packing, etc.
"""

import argparse
import asyncio
import os
import shutil
import sys
from pathlib import Path

from dotenv import load_dotenv
from tripo3d import TripoClient, TaskStatus


SUPPORTED_FORMATS = ["GLTF", "USDZ", "FBX", "OBJ", "STL", "3MF"]
SUPPORTED_TEXTURE_FORMATS = ["JPEG", "PNG"]


async def convert_model(
    task_id: str,
    output_format: str = "GLTF",
    face_limit: int | None = None,
    quad: bool = False,
    force_symmetry: bool = False,
    pivot_to_center_bottom: bool = False,
    flatten_bottom: bool = False,
    flatten_bottom_threshold: float = 0.01,
    texture_size: int = 4096,
    texture_format: str = "JPEG",
    output_path: str | None = None,
) -> Path:
    """
    Convert and optimize a 3D model using Tripo API.

    Args:
        task_id: The task ID of the original model
        output_format: Target format (GLB/GLTF/USDZ/FBX/OBJ/STL/3MF)
        face_limit: Maximum number of faces for decimation
        quad: Enable quad mesh output
        force_symmetry: Force model symmetry
        pivot_to_center_bottom: Move pivot to center bottom
        flatten_bottom: Flatten the bottom of the model
        flatten_bottom_threshold: Threshold for bottom flattening
        texture_size: Texture resolution (default: 4096)
        texture_format: Texture format (JPEG/PNG)
        output_path: Output file path (optional)

    Returns:
        Path to the converted model file
    """
    api_key = os.environ.get("TRIPO_API_KEY")
    if not api_key:
        raise ValueError("TRIPO_API_KEY environment variable is not set")
    base_url = os.environ.get("TRIPO_API_BASE_URL")
    if base_url:
        print(f"Using custom Tripo API base URL: {base_url}")
        TripoClient.BASE_URL = base_url

    if output_format not in SUPPORTED_FORMATS:
        raise ValueError(
            f"Unsupported format: {output_format}. Supported: {SUPPORTED_FORMATS}"
        )

    if texture_format not in SUPPORTED_TEXTURE_FORMATS:
        raise ValueError(
            f"Unsupported texture format: {texture_format}. "
            f"Supported: {SUPPORTED_TEXTURE_FORMATS}"
        )

    print(f"Original task: {task_id}")
    print(f"Target format: {output_format}")
    if face_limit:
        print(f"Face limit: {face_limit}")
    if quad:
        print("Quad mesh: enabled")
    if force_symmetry:
        print("Force symmetry: enabled")
    print("Converting model...")

    async with TripoClient(api_key=api_key) as client:
        convert_kwargs = {
            "original_model_task_id": task_id,
            "format": output_format,
            "quad": quad,
            "force_symmetry": force_symmetry,
            "pivot_to_center_bottom": pivot_to_center_bottom,
            "flatten_bottom": flatten_bottom,
            "flatten_bottom_threshold": flatten_bottom_threshold,
            "texture_size": texture_size,
            "texture_format": texture_format,
        }
        if face_limit is not None:
            convert_kwargs["face_limit"] = face_limit

        convert_task_id = await client.convert_model(**convert_kwargs)
        print(f"Convert task submitted: {convert_task_id}")

        task = await client.wait_for_task(convert_task_id, verbose=True)

        if task.status != TaskStatus.SUCCESS:
            raise RuntimeError(f"Conversion failed with status: {task.status}")

        print("Model conversion completed!")

        # Determine output directory
        if output_path:
            out_file = Path(output_path)
            download_dir = out_file.parent if out_file.parent != Path() else Path(".")
        else:
            download_dir = Path(".")

        download_dir.mkdir(parents=True, exist_ok=True)

        downloaded = await client.download_task_models(task, str(download_dir))

        # Find the main model file
        model_file = None
        for model_type in ["model", "pbr_model", "base_model"]:
            if model_type in downloaded and downloaded[model_type]:
                file_path = downloaded[model_type]
                print(f"Downloaded {model_type}: {file_path}")
                if model_file is None:
                    model_file = Path(file_path)

        for model_type, file_path in downloaded.items():
            if model_type not in ["model", "pbr_model", "base_model"] and file_path:
                print(f"Downloaded {model_type}: {file_path}")

        if model_file:
            if output_path:
                final_path = Path(output_path)
            else:
                ext = model_file.suffix
                final_path = download_dir / f"converted{ext}"

                counter = 1
                while final_path.exists():
                    final_path = download_dir / f"converted_{counter}{ext}"
                    counter += 1

            if model_file != final_path:
                shutil.move(str(model_file), str(final_path))

            print(f"Model saved to: {final_path}")
            return final_path

        raise RuntimeError("No model file was downloaded")


async def main():
    parser = argparse.ArgumentParser(
        description="Convert and optimize 3D models using Tripo API"
    )
    parser.add_argument(
        "task_id",
        type=str,
        help="Task ID of the original model to convert",
    )
    parser.add_argument(
        "--format",
        type=str,
        default="GLTF",
        choices=SUPPORTED_FORMATS,
        dest="output_format",
        help="Target output format (default: GLB)",
    )
    parser.add_argument(
        "--face-limit",
        type=int,
        default=None,
        help="Maximum number of faces (decimation)",
    )
    parser.add_argument(
        "--quad",
        action="store_true",
        help="Enable quad mesh output (forces FBX format)",
    )
    parser.add_argument(
        "--force-symmetry",
        action="store_true",
        help="Force model symmetry",
    )
    parser.add_argument(
        "--pivot-to-center-bottom",
        action="store_true",
        help="Move pivot point to center bottom",
    )
    parser.add_argument(
        "--flatten-bottom",
        action="store_true",
        help="Flatten the bottom of the model",
    )
    parser.add_argument(
        "--flatten-bottom-threshold",
        type=float,
        default=0.01,
        help="Threshold for bottom flattening (default: 0.01)",
    )
    parser.add_argument(
        "--texture-size",
        type=int,
        default=4096,
        help="Texture resolution (default: 4096)",
    )
    parser.add_argument(
        "--texture-format",
        type=str,
        default="JPEG",
        choices=SUPPORTED_TEXTURE_FORMATS,
        help="Texture format (default: JPEG)",
    )
    parser.add_argument(
        "-o", "--output",
        type=str,
        default=None,
        help="Output file path (default: converted.glb)",
    )

    args = parser.parse_args()

    try:
        await convert_model(
            task_id=args.task_id,
            output_format=args.output_format,
            face_limit=args.face_limit,
            quad=args.quad,
            force_symmetry=args.force_symmetry,
            pivot_to_center_bottom=args.pivot_to_center_bottom,
            flatten_bottom=args.flatten_bottom,
            flatten_bottom_threshold=args.flatten_bottom_threshold,
            texture_size=args.texture_size,
            texture_format=args.texture_format,
            output_path=args.output,
        )
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    load_dotenv(dotenv_path=".genix.env", override=True)
    asyncio.run(main())
